### ISSUE TITLE
broken after upgrade from 1.1.13 to 1.2.16

### ISSUE THREAD

**Issue by vsdotnetguy** [devbridge/jQuery-Autocomplete#315]
Hello Tomas,

Previously, we've been using version 1.1.13.  However, new requirements demanded the need for the beforeRender event so we tried to upgraded to version 1.2.16.

However, now when the app is run from Chrome it returns the following errors when running the same code as before with version 1.1.13:
Uncaught TypeError: undefined is not a function. (error occurs on $(selector).autocomplete)
Uncaught Error: Mismatched anonymous define() module: (error occurs in RequireJS version 2.1.6)

Here is the code block in question:
            $.cachedScriptExtension(app.getBaseUrl() + 'Scripts/jquery.autocomplete.min.js').done(function (script, textStatus) {
                $("#" + clientId).autocomplete({
                    serviceUrl: serviceUrl,
                    minChars: 2,
                    onSelect: onSelectCallback
                });
            });

It looks like AMD might be an issue.  Is there anyway to run your autocomplete without AMD.  Can we remove the AMD code so these errors are not encountered?  If so, how and where do we remove the code?

The app currently loads and caches the jquery.autocomplete.min.js script using a jquery based cachedScriptExtension method with the following code:

            /// Includes and caches the specified script file.
            $.cachedScriptExtension = function (url, options) {
                // allow user to set any option except for dataType, cache, and url
                options = $.extend(options || {}, {
                    dataType: "script",
                    cache: true,
                    url: url
                });
                // Use $.ajax() since it is more flexible than $.getScript.
                // Return the jqXHR object so we can chain callbacks
                return $.ajax(options);
            };

Even when we added a script tag to the header and did not use the cachedScriptExtension method, the same error was encountered.

We also tried using the devbridgeAutocomplete alias with no luck.

We're running jQuery version 1.8.3.

TIA
Bob Baldwin
aka VSDotNetGuy

**Comment by tkirda** [comment]
Hi Bob, looks like the problem is because it's loaded by jquery and then RequireJS can not identify the module. Should be straightforward fix. Just replace line 17:

    define(['jquery'], factory);

With:

    factory(jQuery);

And everything should work. Also, keep in mind that there are breaking changes when upgrading from 1.1 to 1.2.
